#!/bin/bash

[[ -z $1 ]] && echo 'Need the path of the script.' && exit 1
[[ ! -f $1 ]] && echo 'Nonexistent path.' && exit 1

path="$( realpath $1 )"
pathWithoutExt="$( basename $path )"
pathWithoutExt="${pathWithoutExt%%.*}"

echo $path $pathWithoutExt

if [[ -f "/usr/bin/$pathWithoutExt" ]]; then 
    echo -n "/usr/bin/$pathWithoutExt already exists. Overwrite? (yes/no)" 
    read resp 
    if [[ $resp =~ yes ]]; then  
	rm /usr/bin/$pathWithoutExt
	echo "Overwriting."
    else
	echo 'Exiting.' 
	exit 1 
    fi
fi

prog="$( cat $path | grep '#!' )"
dontAddShebang=0

[[ -n $prog ]] && dontAddShebang=1

if [[ -z $prog ]]; then
    e=0
    dontAddShebang=0
    while [[ $e -eq 0 ]]; do
	echo '>> There is no shabang present. Provide the shebang string. eg. #!/usr/bin/zsh'
	echo -n '>> '
	read prog
	[[ -z $prog ]] && echo '(need an input)' &&  continue
	prog="$( echo $prog | sed 's/^\s*//; s/\s*$//;' )"
	echo "Using <$prog> to execute <$path>"
	e=1
    done
fi


if [[ $dontAddShebang -eq 0 ]]; then 
	tempfile="$(mktemp)"
	echo 'Using a user provided shebang'
	echo -e "$prog\n\n" >> $tempfile
	cat $path >> $tempfile
	cp $tempfile $path
fi

ln -s $path /usr/bin/$pathWithoutExt 
chmod +x /usr/bin/$pathWithoutExt


	
