#!/bin/bash

TEMPFILE=
URL="https://www.civilsdaily.com/"
PAGE_WITH_NUM=()
DEST=$HOME/Work/CivilsDaily
HELP="$0: Download civilsdaily articles\n
    -d [PATH] Destination directory [default=~/Work/CivilsDaily]\n
    -n [INT]  Number of pages to download [default=1]"

function download_articles() {
    egrep -io 'https://www.civilsdaily.com/news/[^"]+' $TEMPFILE |\
        parallel -j 4\
        wget -q {} -O "$DEST/{= s|https://www.civilsdaily.com/news/([^/]+)/|\$1| =}" :::: -
}

function download_root_url() {
    echo "downloading> $1"
    local root_url="$1"
    TEMPFILE=$(mktemp)
    wget -q $root_url -O $TEMPFILE
}

function get_pages() {
    for i in $(seq 1 $TILL); do
        PAGE_WITH_NUM+=("${URL}page/$i/")
    done
}

function download_pages() {
    for i in ${PAGE_WITH_NUM[@]}; do
        download_root_url $i
        download_articles
    done
}

while getopts "hd:n:" o; do
    case $o in
        h)
            echo -e $HELP; exit 0
            ;;

        d)
            if [[ -n $OPTARG ]]; then
                [[ -d $OPTARG ]] && DEST="$OPTARG" || echo "Invalid path: $OPTARG" && exit 1
            else
                [[ ! -d $DEST ]] && echo "Creating default dir: [~/Work/CivilsDaily]" && mkdir $DEST
            fi
            ;;
        n)
            if [[ -n $OPTARG ]]; then
                [[ ! $OPTARG =~ ^[0-9]+$ ]] && echo "Invalid number provided." && exit 1
                [[ $OPTARG  =~ ^0$ ]] && echo "0 pages?" && exit 1
                TILL=$OPTARG
            fi
            ;;
    esac
done

shift $[ OPTIND -1 ]

get_pages
download_pages
