#!/usr/bin/perl -w

use warnings;
use strict; 

my $help = "$0: Connect to an existing tmux session. 
arg 1: Name of the terminal to be used (default: terminator)
If the arg 1 is provided in the fmt: 's:urvt --hold -e ', this particular string will be used. 
    ";

die "$help\n" if (defined $ARGV[0] and $ARGV[0] =~ /help/); 
my $terminal = $ARGV[0] ? $ARGV[0] : "konsole";
my $cmd = q(%s -e 'tmux -u a -t %s');

unless (substr ($terminal, 0, 2) =~ "s:")  {
    die "No such terminal in the system: $terminal.\n" unless -f "/usr/bin/$terminal"; 
} else {
    $terminal = substr $terminal, 2;
    my $t = $terminal =~ s/\s.*$//ri;
    die "No such terminal in the system: $t.\n" unless -f sprintf "/usr/bin/%s", $t; 
}

if (qx(ps -U \$USER | grep -v grep | grep tmux) =~ /tmux:\s*server/) {
    my $latest = qx(tmux ls | grep '^[0-9]' | tail -n 1 | cut -d':' -f 1);
    chomp $latest;
    $cmd = sprintf $cmd, $terminal, $latest; 
} else {
    $cmd = "$terminal -e 'tmux' "; 
}

my $tempfile = qx(mktemp);
chomp $tempfile;
open my $FH, ">", $tempfile;
print $FH $cmd . "\n"; 
close $FH;
qx(bash $tempfile); 




