#!/bin/bash

function die () {
    local reason="$1"
    echo -e "$1"
    exit 1;
}

HELP="$0: Make a default .desktop in order to quickly deploy it.\n
-n [STR] Name\n
-e [STR] Command\n
-d [STR] Destination directory [default:~/.config/autostart]\n
-o [STR] Only execute this in [which WM[s]?] (default:i3;awesome;) If multiple wm then separate with '::'\n
-i [STR] Icon name
"

ICON=""
NAME=""
DEST="$HOME/.config/autostart"
EXEC=""
ONLY="i3;awesome;"

while getopts ":n:e:d:h" o; do
    case $o in
	i) ICON="$OPTARG" ;;
	n) NAME="$OPTARG" ;;
	d) DEST="$OPTARG" ;;
	e) EXEC="$OPTARG" ;;
	o) ONLY="$OPTARG" ;;
	h) echo -e $HELP
	   exit 0 ;;
    esac
done

OPTIND=$[OPTIND - 1]
[[ $* = "" ]] && die 'Provide -h for help'
[[ ! -d $DEST ]]  && die 'Path does not exist.'
[[ ! $NAME ]] && die "-n [STR] required"
[[ ! $EXEC ]] && die "-e [STR] required"

DEST="$(realpath $DEST)"
ONLY="${ONLY//::/;}"
STRING="[Desktop Entry]\nName=$NAME\nIcon=$ICON\nExec=$EXEC\nType=Application\nStartupNotify=true\nOnlyShowIn=$ONLY\n"

DEST="$DEST/$NAME.desktop"
echo -e $STRING > $DEST
