#!/usr/bin/perl -W

my $IN = "";
my $TEMP = "";
my $USE = "emacs";
my $SERVER = 0;
my $CONF = 1;
my $HELP = "$0: Open emacsclient | (noconfig) emacs | emacs using stdin.
ARG 1: noconf: Use 'emacs -q'

Caveats:
If emacs server is running then use emacsclient or else if noconf is specified then use 'emacs -q' or else use emacs.
";

sub death {
    my $msg = $_[0];
    die "$msg\n";
}

if (defined($ARGV[0])) {
    $ARGV[0] =~ /^--?h(elp)?/ and death($HELP);
    $CONF = $ARGV[0] =~ /noconf/ ? 0 : 1;
} else {

}

# get stdin
while (my $line = <STDIN>) {
    $IN .= $line if $line;
}
chomp $IN;
death("No stdin provided.") if $IN !~ /[a-z]/;

$SERVER = qx(ps aux | egrep -- "emacs --(bg|fg)-daemon") ne "" ? 1 : 0;
$USE = $SERVER ? "emacsclient -c" : $CONF ? "emacs" : "emacs -q";
$USE = "emacs -q" unless $CONF;
$TEMP = qx(mktemp); chomp $TEMP;

if ($USE !~ /emacsclient/) {
    $USE =~ s/^(emacs)/$1 $TEMP --no-splash --eval "(read-only-mode)" -fn "DejaVu Sans Mono 11" -bg "#282a2e" -fg "#6affee"/;
} else {
    $USE .= " $TEMP";
}

# write to file and start emacs
my $FH;
open($FH, ">", $TEMP);
print $FH $IN;
close($FH);

# launch emacs with stdin
qx($USE);
qx(rm $TEMP);
