#!/bin/bash

[[ $UID -ne 0 ]] && echo 'Script should be run with sudo'

echo 'Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "Tapping" "on"
EndSection' > /etc/X11/xorg.conf.d/40-libinput.conf

echo 'Please restart your display manager'
