#!/bin/bash

[[ -z $1 ]] && echo "No path provided." && exit 1

filename=$( realpath $1 )
e=${filename##*.}
x=""

case $e in
     go) x="go run"        ;; 
     py) x=python3.9    ;;
     pm) x=perl ;; 
     pl) x=perl	      ;;
     bash) x=bash     ;;
     sh) x=bash	      ;;
     zsh) x=zsh	      ;;
     lua) x=lua	      ;;
     lisp) x=clisp    ;;
     js) x=node	      ;;
     c)  x="bash /home/caligian/bin/crun" ;;
     *) echo 'cannot execute this.'; exit 1 ;;
esac

$x $filename &>/dev/stdout
     
     
     







