#!/bin/bash

[[ -z $1 ]] && echo 'no arg provided. provide an INT for workspace.' && exit 1

cmd="i3-msg"
[[ -n 2 ]] && cmd="i3-msg"

[[ -n $1 ]] && [[ $1 -gt 10 ]] || [[ $1 -lt 0 ]] && echo 'invalid index.' && exit

target=$[$1 - 1]

IFS=$'\n'

workspaces=($($cmd -t get_workspaces | perl -M'JSON' -0777 -e '$json = decode_json(<>); foreach my $hashref (@$json) { print $hashref->{name}, "@", $hashref->{visible} == 0 ? "false" : "true", "\n" }'))

unset IFS

availableWorkspaces=(1 2 3 4 5 6 7 8 9 10)

target=${availableWorkspaces[$target]}

active=""
echo $workspaces
for i in ${workspaces[@]}; do
    if [[ $i =~ 'true' ]]; then
	active=${i%%@*}
	break
    fi
done

$cmd "rename workspace \"$active\" to temp; rename workspace \"$target\" to \"$active\"; rename workspace temp to \"$target\"; " &>/dev/null
