#!/bin/bash

[[ $UID -ne 0 ]] && echo Please run as root. && exit 1
[[ -z $1 ]] && echo 'No parameter provided.' && exit 1

help="$0: Install stardict dictionaries.
Parameters : Specific all the paths in which the dictionaries are present. 
Assumed Extensions : .ifo, .idx, .dict.dz
Make sure that all the parameters are quoted."

[[ $1 =~ help|-h ]] && echo $help && exit 1

filePaths=("$@")
for i in $(seq 0 ${#filePaths[@]}); do
    ${filePaths[$i]}="$(realpath $filePath[$i])"
done

dest=/usr/share/stardict/dic

[[ ! -d $dest ]] && mkdir -p $dest && echo $dest did not exist before. It does now.

for i in ${filePaths[@]}; do
    find $i -type f -regex '.*\(ifo\|idx\|dict\.dz\)$' -exec cp -v {} /usr/share/stardict/dic \;
done








