#!/bin/bash

TEMPLATE=$(cat <<-EOF
[Unit]
Name=
Description=This is a template Unit file
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/path/to/your/app
User=someUser

[Install]
WantedBy=multi-user.target

EOF
)

HELP="Usage: Make a default template for systemd service and open it in editor set in \$EDITOR
- If ~/.config/systemd/user does not exist, it will created.
- When you are done, rename the file to your liking. 
- If you have not set EDITOR then nvim-qt shall be used."

[[ $1 =~ -h(elp)? ]] && echo "$HELP" && exit 1

DEST=$HOME/.config/systemd/user
[[ ! -d  $DEST ]] && mkdir $DEST

DEST="$DEST/template.service"
echo "$TEMPLATE" > $DEST

EDITOR=${EDITOR:-nvim-qt}
$EDITOR $DEST

