#!/usr/bin/ruby

HELP =<<EOF
Usage: Add/stage git controlled files automatically after regex filtering. 
\$1 
Regex to match the files 

Caveats:
- You should be in a valid git directory
- When no matches are found, nothing will be added/staged. 
- Output of 'git status' will be used to parse the filenames 
EOF

ARGV.length == 0 and raise Exception.new("No input passed. -h for help")
ARGV[0] =~ /-h(elp)?/ and raise Exception.new(HELP) 

regex = Regexp.new(ARGV[0], 'i')
%(git add) =~ /^fatal/i and raise Exception.new("Not a git directory")

%x(git status -s).split("\n").each { |status|
  status, file = status.strip.split(/\s+/)
  status =~ /M/ and %x(git stage #{file})
  status =~ /\?\?/ and %x(git add #{file})
}


