#!/bin/bash

cd ~/.config/i3
rm config

cat user/default.i3 >> config
cat user/theme.i3 >> config
cat user/modes.i3 >> config
cat user/bar.i3 >> config
cat user/rules.i3 >> config
cat user/startup.i3 >> config

i3-msg restart
