#!/bin/bash

home=/home/caligian/
wallpaperloc=${home}/Wallpapers/current

if [[ ! -h $wallpaperloc ]]; then 
    echo 'Please symlink the wallpaper directory to '$HOME/wallpaper/current
    exit
fi

[[ -n $1 ]] && useSway=1

IFS=$'\n'
wallpapers=($( find -L $wallpaperloc -regex '.*\(jpg\|png\)'  ))
[[ ${#wallpapers[@]} -eq 0 ]] && echo 'No wallpapers found. Download some.' && exit 1
unset IFS
randomWallpaper="${wallpapers[ $[ RANDOM%${#wallpapers[@]} ] ]}"
echo $randomWallpaper

if [[ $useSway -eq 1 ]]; then
    swaybg -i "$randomWallpaper" -m fill
    exit 
else
    feh --bg-center $randomWallpaper
fi
